In [1]:
import math
import os
import random
import cv2
import numpy as np
import Augmentor

In [2]:
headpath = os.getcwd()
list = os.listdir()
for i in ["dataset.ipynb","Test.npy","Train.npy","Val.npy"]:
	try:
		list.remove(i)
	except Exception as error:
		pass
countdict = {}
print(f"Headpath : {headpath}")
print(f"Categories : {list}")

Headpath : d:\Dataset of currency\Denomination
Categories : ['10-New', '10-Old', '100-New', '100-Old', '20-New', '20-Old', '200', '2000', '50-New', '50-Old', '500']


In [9]:
for i in list:
	actual_count = len(os.listdir(os.path.join(headpath,i)))
	countdict[i] = actual_count

for i in countdict.keys():
	print(i,countdict[i])

10-New 3
10-Old 3
100-New 3
100-Old 3
20-New 3
20-Old 3
200 3
2000 3
50-New 3
50-Old 3
500 3


In [4]:
for folder in countdict.keys():
	images = os.listdir(os.path.join(headpath,folder))
	print(f"Images in {folder} : {len(images)}")
	for image in images:
		try:
			img = cv2.imread(os.path.join(headpath,folder,image))
			if img.shape[0] > img.shape[1]:
				img = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)
				cv2.imwrite(os.path.join(headpath,folder,image),img)
		except Exception as error:
			print(image,error)

Images in 10-New : 200
Images in 10-Old : 271
Images in 100-New : 229
Images in 100-Old : 118
Images in 20-New : 113
Images in 20-Old : 301
Images in 200 : 366
Images in 2000 : 205
Images in 50-New : 172
Images in 50-Old : 129
Images in 500 : 203


In [5]:
for folder in countdict.keys():
	images = os.listdir(os.path.join(headpath,folder))
	print(f"Images in {folder} : {len(images)}")
	for image in images:
		try:
			img = cv2.imread(os.path.join(headpath,folder,image))
			img = cv2.resize(img,(300,200))
			cv2.imwrite(os.path.join(headpath,folder,image),img)
		except Exception as e:
			print(image,e)

Images in 10-New : 200
Images in 10-Old : 271
Images in 100-New : 229
Images in 100-Old : 118
Images in 20-New : 113
Images in 20-Old : 301
Images in 200 : 366
Images in 2000 : 205
Images in 50-New : 172
Images in 50-Old : 129
Images in 500 : 203


In [6]:
for folder,count in countdict.items():
	train = round(count*0.7)
	val = (count - train)//2
	test = val

	images = os.listdir(folder)
	random.shuffle(images)
	trainimg = images[:train]
	valimg = images[train:train+val]
	testimg = images[train+val:]

	for i in ["Train","Val","Test"]:
		if not os.path.exists(os.path.join(headpath,folder,i)):
			os.mkdir(os.path.join(headpath,folder,i))

	for i in trainimg:
		os.replace(os.path.join(headpath,folder,i),os.path.join(headpath,folder,"Train",i))
	
	for i in valimg:
		os.replace(os.path.join(headpath,folder,i),os.path.join(headpath,folder,"Val",i))

	for i in testimg:
		os.replace(os.path.join(headpath,folder,i),os.path.join(headpath,folder,"Test",i))	

In [3]:
costdict = {"Train":700,"Val":150,"Test":150}

In [5]:
for folder in countdict.keys():
	for categoryfolder,samples in costdict.items():
		print(f"For {folder} {categoryfolder}:")
		p = Augmentor.Pipeline(os.path.join(headpath,folder,categoryfolder))
		p.rotate180(probability=0.5)
		p.shear(probability=0.5,max_shear_left=10,max_shear_right=10)
		p.flip_left_right(probability=0.5)
		p.random_contrast(probability=0.3,min_factor=0.7,max_factor=1)
		p.random_brightness(probability=0.7,min_factor=0.8,max_factor=1.2)
		p.sample(samples)

For 10-New Train:
Initialised with 140 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-New\Train\output.

Processing <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=300x200 at 0x1D4B9F0C310>: 100%|██████████| 700/700 [00:04<00:00, 171.22 Samples/s]


For 10-New Val:
Initialised with 30 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-New\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9EF84C0>: 100%|██████████| 150/150 [00:00<00:00, 188.83 Samples/s]                  


For 10-New Test:
Initialised with 30 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-New\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB5A50>: 100%|██████████| 150/150 [00:00<00:00, 215.34 Samples/s]                  


For 10-Old Train:
Initialised with 190 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-Old\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E95AE0>: 100%|██████████| 700/700 [00:03<00:00, 186.86 Samples/s]                  


For 10-Old Val:
Initialised with 40 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-Old\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E7AF50>: 100%|██████████| 150/150 [00:00<00:00, 196.69 Samples/s]


For 10-Old Test:
Initialised with 41 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\10-Old\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E94A90>: 100%|██████████| 150/150 [00:00<00:00, 196.21 Samples/s]                  


For 100-New Train:
Initialised with 160 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-New\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9F0CAF0>: 100%|██████████| 700/700 [00:03<00:00, 192.00 Samples/s]                  


For 100-New Val:
Initialised with 34 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-New\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9EFB8B0>: 100%|██████████| 150/150 [00:00<00:00, 188.62 Samples/s]                  


For 100-New Test:
Initialised with 35 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-New\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB5840>: 100%|██████████| 150/150 [00:00<00:00, 191.34 Samples/s]                  


For 100-Old Train:
Initialised with 83 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-Old\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E97790>: 100%|██████████| 700/700 [00:03<00:00, 210.29 Samples/s]                  


For 100-Old Val:
Initialised with 17 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-Old\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E7B970>: 100%|██████████| 150/150 [00:00<00:00, 153.57 Samples/s]                


For 100-Old Test:
Initialised with 18 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\100-Old\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9CE2CB0>: 100%|██████████| 150/150 [00:01<00:00, 117.80 Samples/s]                 


For 20-New Train:
Initialised with 79 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-New\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9ED9D50>: 100%|██████████| 700/700 [00:03<00:00, 189.68 Samples/s]                  


For 20-New Val:
Initialised with 17 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-New\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9CE38B0>: 100%|██████████| 150/150 [00:00<00:00, 215.56 Samples/s]


For 20-New Test:
Initialised with 17 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-New\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB5A80>: 100%|██████████| 150/150 [00:00<00:00, 175.83 Samples/s]                


For 20-Old Train:
Initialised with 211 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-Old\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E96230>: 100%|██████████| 700/700 [00:03<00:00, 188.68 Samples/s]                  


For 20-Old Val:
Initialised with 45 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-Old\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB59C0>: 100%|██████████| 150/150 [00:00<00:00, 180.49 Samples/s]                  


For 20-Old Test:
Initialised with 45 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\20-Old\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E94790>: 100%|██████████| 150/150 [00:00<00:00, 154.27 Samples/s]                  


For 200 Train:
Initialised with 256 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\200\Train\output.

Processing <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=300x200 at 0x1D4B9CE3B20>: 100%|██████████| 700/700 [00:03<00:00, 176.20 Samples/s]


For 200 Val:
Initialised with 55 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\200\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E5FA00>: 100%|██████████| 150/150 [00:00<00:00, 178.35 Samples/s]                


For 200 Test:
Initialised with 55 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\200\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E95570>: 100%|██████████| 150/150 [00:00<00:00, 203.21 Samples/s]                


For 2000 Train:
Initialised with 144 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\2000\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB56F0>: 100%|██████████| 700/700 [00:04<00:00, 160.20 Samples/s]                  


For 2000 Val:
Initialised with 30 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\2000\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9EE0F40>: 100%|██████████| 150/150 [00:00<00:00, 183.38 Samples/s]                  


For 2000 Test:
Initialised with 31 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\2000\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E7BD90>: 100%|██████████| 150/150 [00:00<00:00, 167.34 Samples/s]                


For 50-New Train:
Initialised with 120 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-New\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E94280>: 100%|██████████| 700/700 [00:03<00:00, 198.31 Samples/s]                  


For 50-New Val:
Initialised with 26 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-New\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E5FD60>: 100%|██████████| 150/150 [00:00<00:00, 178.72 Samples/s]                 


For 50-New Test:
Initialised with 26 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-New\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E96770>: 100%|██████████| 150/150 [00:00<00:00, 195.99 Samples/s]                  


For 50-Old Train:
Initialised with 90 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-Old\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB4E20>: 100%|██████████| 700/700 [00:04<00:00, 171.68 Samples/s]                  


For 50-Old Val:
Initialised with 19 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-Old\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9EE0BB0>: 100%|██████████| 150/150 [00:00<00:00, 152.75 Samples/s]                  


For 50-Old Test:
Initialised with 20 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-Old\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4A8BB5480>: 100%|██████████| 150/150 [00:00<00:00, 157.61 Samples/s]                


For 500 Train:
Initialised with 142 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\500\Train\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E96710>: 100%|██████████| 700/700 [00:03<00:00, 214.83 Samples/s]                  


For 500 Val:
Initialised with 30 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\500\Val\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E5D1B0>: 100%|██████████| 150/150 [00:00<00:00, 209.63 Samples/s]                  


For 500 Test:
Initialised with 31 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\500\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1D4B9E97340>: 100%|██████████| 150/150 [00:00<00:00, 209.23 Samples/s]


In [7]:
for category in ["Train","Val","Test"]:
	for folder in countdict.keys():
		images = os.listdir(os.path.join(headpath,folder,category,"output"))
		print(f"Images in {folder} {category} : {len(images)}")
		for image in images:
			try:
				img = cv2.imread(os.path.join(headpath,folder,category,"output",image))
				if img.shape[0] > img.shape[1]:
					img = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)
					cv2.imwrite(os.path.join(headpath,folder,category,"output",image),img)
			except Exception as error:
				print(image,error)

Images in 10-New Train : 700
Images in 10-Old Train : 700
Images in 100-New Train : 700
Images in 100-Old Train : 700
Images in 20-New Train : 700
Images in 20-Old Train : 700
Images in 200 Train : 700
Images in 2000 Train : 700
Images in 50-New Train : 700
Images in 50-Old Train : 700
Images in 500 Train : 700
Images in 10-New Val : 150
Images in 10-Old Val : 150
Images in 100-New Val : 150
Images in 100-Old Val : 150
Images in 20-New Val : 150
Images in 20-Old Val : 150
Images in 200 Val : 150
Images in 2000 Val : 150
Images in 50-New Val : 150
Images in 50-Old Val : 150
Images in 500 Val : 150
Images in 10-New Test : 150
Images in 10-Old Test : 150
Images in 100-New Test : 150
Images in 100-Old Test : 150
Images in 20-New Test : 150
Images in 20-Old Test : 150
Images in 200 Test : 150
Images in 2000 Test : 150
Images in 50-New Test : 150
Images in 50-Old Test : 150
Images in 500 Test : 150


In [11]:
labellist = ['10-New', '10-Old', '100-New', '100-Old', '20-New', '20-Old', '200', '2000', '50-New', '50-Old', '500']

In [9]:
for category in ["Train","Val","Test"]:
	print(category)
	mainArray = []
	for folder in countdict.keys():
		label = labellist.index(folder)
		print(f"Processing {folder} {labellist[label]}:")
		label = np.array([label])
		images = os.listdir(os.path.join(headpath,folder,category,"output"))
		for image in images:
			try:
				img = cv2.imread(os.path.join(headpath,folder,category,"output",image))
				img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
				img = np.array(img)
				mainArray.append([img,label])
			except Exception as e:
				print(image,e)
		np.save(f"{category}.npy",mainArray)

Train
Processing 10-New 10-New:


c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


Processing 10-Old 10-Old:
Processing 100-New 100-New:
Processing 100-Old 100-Old:
Processing 20-New 20-New:
Processing 20-Old 20-Old:
Processing 200 200:
Processing 2000 2000:
Processing 50-New 50-New:
Processing 50-Old 50-Old:
Processing 500 500:
Val
Processing 10-New 10-New:
Processing 10-Old 10-Old:
Processing 100-New 100-New:
Processing 100-Old 100-Old:
Processing 20-New 20-New:
Processing 20-Old 20-Old:
Processing 200 200:
Processing 2000 2000:
Processing 50-New 50-New:
Processing 50-Old 50-Old:
Processing 500 500:
Test
Processing 10-New 10-New:
Processing 10-Old 10-Old:
Processing 100-New 100-New:
Processing 100-Old 100-Old:
Processing 20-New 20-New:
Processing 20-Old 20-Old:
Processing 200 200:
Processing 2000 2000:
Processing 50-New 50-New:
Processing 50-Old 50-Old:
Processing 500 500:


## Test

In [3]:
train = np.load(os.path.join(headpath,"Test.npy"),allow_pickle=True)

In [4]:
train_features = [i[0] for i in train]
train_classes = [i[1] for i in train]

In [5]:
train_classes

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [6]:
traint = np.array(train_classes)

In [7]:
traint.flatten()

array([ 0,  0,  0, ..., 10, 10, 10])

In [8]:
for i in range(11):
  print(np.count_nonzero(traint == i))

150
150
150
150
150
150
150
150
150
150
150


## Resolving 1 image issue in 50 Old Test

In [4]:
p = Augmentor.Pipeline(os.path.join(headpath,'50-Old','Test'))
p.rotate180(probability=0.5)
p.shear(probability=0.5,max_shear_left=10,max_shear_right=10)
p.flip_left_right(probability=0.5)
p.random_contrast(probability=0.3,min_factor=0.7,max_factor=1)
p.random_brightness(probability=0.7,min_factor=0.8,max_factor=1.2)
p.sample(150)

Initialised with 19 image(s) found.
Output directory set to d:\Dataset of currency\Denomination\50-Old\Test\output.

Processing <PIL.Image.Image image mode=RGB size=300x200 at 0x1A83684E950>: 100%|██████████| 150/150 [00:00<00:00, 211.11 Samples/s]                


In [7]:
images = os.listdir(os.path.join(headpath,'50-Old','Test',"output"))
print(f"Images in 50-Old Test : {len(images)}")
for image in images:
	try:
		img = cv2.imread(os.path.join(headpath,'50-Old','Test',"output",image))
		if img.shape[0] > img.shape[1]:
			img = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)
			cv2.imwrite(os.path.join(headpath,'50-Old','Test',"output",image),img)
	except Exception as error:
		print(image,error)

Images in 50-Old Test : 150


In [12]:
for category in ["Test"]:
	print(category)
	mainArray = []
	for folder in countdict.keys():
		label = labellist.index(folder)
		print(f"Processing {folder} {labellist[label]}:")
		label = np.array([label])
		images = os.listdir(os.path.join(headpath,folder,category,"output"))
		for image in images:
			try:
				img = cv2.imread(os.path.join(headpath,folder,category,"output",image))
				img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
				img = np.array(img)
				mainArray.append([img,label])
			except Exception as e:
				print(image,e)
		np.save(f"{category}.npy",mainArray)

Test
Processing 10-New 10-New:


c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


Processing 10-Old 10-Old:
Processing 100-New 100-New:
Processing 100-Old 100-Old:
Processing 20-New 20-New:
Processing 20-Old 20-Old:
Processing 200 200:
Processing 2000 2000:
Processing 50-New 50-New:
Processing 50-Old 50-Old:
Processing 500 500:
